name: Build & Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9a-zA-Z]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish
        env:
          NOXCREW_MAVEN_PUBLIC_USERNAME: ${{ secrets.NOXCREW_MAVEN_PUBLIC_USERNAME }}
          NOXCREW_MAVEN_PUBLIC_PASSWORD: ${{ secrets.NOXCREW_MAVEN_PUBLIC_PASSWORD }}

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: api/build/libs/sheeplib-+([0-9]).+([0-9]).+([0-9a-zA-Z]).jar
          draft: true
